apiVersion: v1
kind: Namespace
metadata:
  name: product-mgmt-prod
  labels:
    name: product-mgmt-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: product-mgmt-staging
  labels:
    name: product-mgmt-staging
    environment: staging
