apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: product-mgmt-prod
type: Opaque
stringData:
  username: postgres
  password: CHANGE_ME_IN_PRODUCTION
  business-db-url: jdbc:postgresql://postgres-service:5432/business_db
  iam-db-url: jdbc:postgresql://postgres-service:5432/iam_db
  process-db-url: jdbc:postgresql://postgres-service:5432/process_db
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: product-mgmt-prod
type: Opaque
stringData:
  username: admin
  password: CHANGE_ME_IN_PRODUCTION
  host: rabbitmq-service
  port: "5672"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: product-mgmt-prod
type: Opaque
stringData:
  password: CHANGE_ME_IN_PRODUCTION
  host: redis-service
  port: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: product-mgmt-prod
type: Opaque
stringData:
  admin-username: admin
  admin-password: CHANGE_ME_IN_PRODUCTION
  client-secret: gateway-client-secret-change-in-production
